Api/health
KryptonReborn/blockfrost-kotlin-sdk pull request #2
Opened 2024-05-27 13:23 UTC by hieu-dd

# Pull Request (PR) Summary

- Describe the main changes in this PR.
- Mention the issue(s) this PR addresses.

## Changes Description

Please provide a detailed description of the changes you have made in this PR.

## Related Issue(s)

- Fixes # (issue number)

## Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Other (please describe)

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] My PR is targeting the `main` branch
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added tests that prove my fix is effective or my feature works
- [ ] All new and existing tests passed.

2024-05-28 14:21 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/const/Const.kt
> +    const val BASE_URL = "https://cardano-mainnet.blockfrost.io"
em thấy api nào cũng có base_url là `https://cardano-mainnet.blockfrost.io/api/v0` hết ạ

2024-05-28 14:21 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/model/ApiRoot.kt
> +    val version: String? = null,
2 field này require ạ

2024-05-28 14:21 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/BlockFrostKotlinSdk.kt
> +object BlockFrostKotlinSdk : BlockFrostKoinComponent() {
xóa file `BlockFrostSdk` đi nhỉ?

2024-05-28 14:21 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/utils/Exception.kt
> +fun Exception.toErrorResponse(): ApiError {
move fun này vào file Exception base luôn ạ

2024-05-28 14:21 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/const/Const.kt
> +    const val BASE_URL = "https://cardano-mainnet.blockfrost.io"
Với lại config nên hỗ trợ nhiều môi trường không chỉ mainnet ạ

2024-05-28 14:48 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/BlockFrostKotlinSdk.kt
> +object BlockFrostKotlinSdk : BlockFrostKoinComponent() {
ý em là file này ạ
```
object BlockFrostSdk {
    fun greet(): String {
        return "Hello, BlockFrost!"
    }
}
```

2024-05-28 15:14 UTC, hieu-dd commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/const/Const.kt
> +    const val BASE_URL = "https://cardano-mainnet.blockfrost.io"
ừ a thêm baseUrl vào config rồi.
https://cardano-mainnet.blockfrost.io/api/v0/health thì host là cardano-mainnet.blockfrost.io với endcodePath là `/health` nên a muốn để base url là https://cardano-mainnet.blockfrost.io tiện việc dùng các path viết unit test luôn

2024-05-28 16:04 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/const/Const.kt
> +    const val BASE_URL = "https://cardano-mainnet.blockfrost.io"
Như vậy thì mỗi path mình lại phải thêm `/api/v0` không để làm gì ạ
![image](https://github.com/KryptonReborn/blockfrost-kotlin-sdk/assets/105967541/ee7a289a-5489-4e67-b25d-a32926f4652f)
Em suggest thế này ạ
```
data class BlockfrostConfig(
    val networkType: NetworkType = NetworkType.Mainnet,
    val projectId: String,
) 

enum class NetworkType(val url: String) {
    Mainnet("https://cardano-mainnet.blockfrost.io/api/v0"),
    Preprod("https://cardano-preprod.blockfrost.io/api/v0"),
    Preview("https://cardano-preview.blockfrost.io/api/v0")
}

```

2024-05-28 16:43 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/BlockFrostKotlinSdk.kt
> +    fun initConfig(config: BlockfrostConfig) {
Chỗ này không có ràng buộc user phải initConfig trước khi gọi các hàm khác cũng hơi confuse ạ

2024-05-28 16:45 UTC, HoangNguyen219 commented on core/src/integrationTest/kotlin/dev/kryptonreborn/blockfrost/excludeBuild/HealthTest.kt
> +            val r = healthApi.getHealth()
Em nghĩ phải test từ hàm `BlockFrostKotlinSdk.getHealth()` chứ ạ. Với lại đọc code thì em cũng chưa biết cách get result như thế nào ạ.

2024-05-29 13:52 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/HealthApi.kt
> +        const val PATH_API_ROOT = "/"
cái này bỏ đi cho gọn ạ

2024-05-29 13:52 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/HealthApi.kt
> +import io.ktor.client.request.get
Remove import dư ạ

2024-05-30 03:34 UTC, HoangNguyen219 approved these changes, later dismissed

2024-05-30 14:39 UTC, iTanChi commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/di/BlockFrostKoinComponent.kt
> +    private val koinApp =
SDK a nghĩ nên hạn chế dùng DI, code thuần và để client dùng SDK tự tích hợp DI nếu thích

2024-05-30 14:41 UTC, iTanChi commented on core/src/commonMain/kotlin/BlockFrostKotlinSdk.kt
> +object BlockFrostKotlinSdk : BlockFrostKoinComponent() {
rename lại là BlockFrost thôi?

2024-05-30 14:41 UTC, iTanChi commented on core/src/commonMain/kotlin/BlockFrostKotlinSdk.kt
> +object BlockFrostKotlinSdk : BlockFrostKoinComponent() {
cái này nên là class và truyền vào config ở constructor

2024-05-30 14:44 UTC, iTanChi commented on core/build.gradle.kts
> +                api(libs.ktorClientOkhttp)
sao phải dùng api nhỉ, bên ngoài a nghĩ ko cần biết là mình dùng ktor

2024-05-30 14:51 UTC, iTanChi commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/HealthRepo.kt
> +internal class HealthRepo(private val healthApi: HealthApi) {
với SDK thì ko cần tầng repo đâu

2024-05-30 14:55 UTC, iTanChi commented on example/composeApp/src/commonMain/kotlin/App.kt
> +                projectId = "mainnet7fToxtolmPU20aln1LrH2brEJOwq4ZoJ",
ko nên hardcode các thông tin này nhé, đưa vào biến env hay config gì đó

2024-05-30 14:59 UTC, iTanChi commented on core/src/jvmTest/kotlin/dev/kryptonreborn/blockfrost/health/HealthApiTest.kt
Chỉ có jvmTest mà ko có commonTest nhỉ

2024-05-30 15:01 UTC, iTanChi commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/utils/Coroutines.kt
> +suspend fun <T> withIO(block: suspend CoroutineScope.() -> T): T =
Default nhưng lại để là withIO à :\ nhưng có cần cái này ko?

2024-05-30 15:03 UTC, iTanChi commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/ktor/Ktor.kt
> +                level = LogLevel.ALL
nhưng cái này quan trọng, nên đưa vào config nè

2024-05-31 07:02 UTC, hieu-dd commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/ktor/Ktor.kt
> +                level = LogLevel.ALL
cái này là sao nhỉ

2024-05-31 10:29 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/BlockFrostKotlinSdk.kt
> +        try {
Chỗ try catch này nên đưa vào chỗ gọi api thì hợp lý hơn ạ

2024-05-31 10:29 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/HealthApi.kt
> +        )
```
    override suspend fun getApiRoot() = handleRequest {
        httpClient.fetchResource<ApiRoot>(blockfrostConfig.networkType.url)
    }
```
Thêm 1 file APIHelper vào utils ạ

```
object ApiHelper {
    inline fun <R> handleRequest(apiCall: () -> R): R {
        return runCatching {
            apiCall()
        }.getOrElse {
            throw it
        }
    }
}
```

2024-05-31 10:29 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/model/ApiRoot.kt
> +    val version: String = "",
Có giá trị default làm gì vậy ạ

2024-05-31 10:29 UTC, HoangNguyen219 commented on core/src/commonTest/kotlin/dev/kryptonreborn/blockfrost/health/HealthApiTest.kt
> +        }
Em nghĩ tạo 1 interface của API rồi mock như này hợp lý hơn ạ 
```
    @Test
    fun testApiSuccess() {
        runTest {
            val healthApiImpl = object : HealthApi {
                override suspend fun getApiRoot(): ApiRoot {
                    return ApiRoot(
                        url = "https://blockfrost.io/",
                        version = "0.1.0"
                    )
                }

                override suspend fun getHealth(): Health {
                    TODO("Not yet implemented")
                }

                override suspend fun getCurrentBackendTime(): Clock {
                    TODO("Not yet implemented")
                }
            }
            BlockFrostKotlinSdk.healthApiImpl = healthApiImpl
            val result = BlockFrostKotlinSdk.getApiRoot()
            assertEquals("0.1.0", result.version)
            assertEquals("https://blockfrost.io/", result.url)
        }
    }
```

2024-05-31 10:29 UTC, HoangNguyen219 commented on core/src/commonTest/kotlin/dev/kryptonreborn/blockfrost/health/HealthApiTest.kt
> +import kotlin.test.DefaultAsserter.assertEquals
Mà anh `import kotlin.test.assertEquals` ấy ạ

2024-05-31 10:29 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/base/ApiResponse.kt
> +        res.statusCode == 400 -> {
```
res.statusCode == HttpStatusCode.BadRequest.value
```

2024-05-31 10:30 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/ktor/Ktor.kt
> +                level = LogLevel.ALL
Ý anh Tân là đưa log level vào config ấy ạ

2024-05-31 10:49 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/base/ApiResponse.kt
> +                res.error ?: "Unknown error",
Mấy string này lặp thì tạo biến ạ

2024-05-31 11:13 UTC, hieu-dd commented on core/src/commonTest/kotlin/dev/kryptonreborn/blockfrost/health/HealthApiTest.kt
> +        }
cái này test API mà, mock thì nó hơi vô nghĩa

2024-05-31 11:17 UTC, hieu-dd commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/HealthApi.kt
> +        )
a thấy tầng API ng ta hay trả về raw response hoặc kệ nó throw error, ng ta hay handle ở tầng repo or cao hơn thôi

2024-05-31 11:22 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/HealthApi.kt
> +        )
chỗ này thì em không rõ nhưng mà dù sao thì cũng tạo 1 hàm để handle không bị lặp code chỗ try catch ạ

2024-05-31 11:30 UTC, hieu-dd commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/ktor/Ktor.kt
> +                level = LogLevel.ALL
cái LogLevel này là của ktor, muốn đưa vô config thì lại tự define các log level của m r map vào à

2024-05-31 11:30 UTC, hieu-dd commented on core/src/commonMain/kotlin/BlockFrostKotlinSdk.kt
> +        try {
a nghĩ là tầng API chỉ nên trả về raw data

2024-05-31 11:31 UTC, hieu-dd commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/HealthApi.kt
> +        )
thế chắc m tạo ở BlockFrostSdk thôi

2024-05-31 12:30 UTC, hieu-dd commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/model/ApiRoot.kt
> +    val version: String = "",
a thấy để default nó đỡ phải check kiểu apiRoot.url?

2024-05-31 12:48 UTC, HoangNguyen219 commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/model/ApiRoot.kt
> +    val version: String = "",
Nó là field required tương tự như field của mấy api kia đâu cần default đâu ạ

2024-05-31 12:50 UTC, hieu-dd commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/health/model/ApiRoot.kt
> +    val version: String = "",
ừ a bỏ đi cũng đc

2024-05-31 15:08 UTC, iTanChi commented on core/build.gradle.kts
> +        val jvmMain by getting {
sao ko có jsMain nhỉ?

2024-05-31 15:08 UTC, iTanChi commented on core/build.gradle.kts
> +        val jvmMain by getting {
check xem có đáp ứng hết các target ko nhé

2024-05-31 15:09 UTC, iTanChi commented on core/build.gradle.kts
> +            dependsOn(integrationTest)
sao jvm test lại depend vào integration test nhỉ

2024-05-31 15:18 UTC, iTanChi commented on core/build.gradle.kts
> +            dependsOn(commonTest)
cái này có cần thiết đâu, bỏ đi

2024-05-31 15:19 UTC, iTanChi commented on core/src/commonMain/kotlin/BlockFrostKotlinSdk.kt
> +object BlockFrostKotlinSdk {
Đổi tên lại là BlockFrostClient nhé, là class truyền vào config khi init

2024-05-31 15:23 UTC, iTanChi commented on core/src/commonTest/kotlin/dev/kryptonreborn/blockfrost/KtorClientTest.kt
> +object KtorClientTest {
Đổi tên là TestKtorClient, class có hậu tố Test thường chứa các testcase

2024-05-31 15:23 UTC, iTanChi commented on core/src/commonTest/kotlin/dev/kryptonreborn/blockfrost/health/HealthApiTest.kt
> +                    {
nên đọc từ json

2024-05-31 15:23 UTC, iTanChi commented on core/src/commonTest/kotlin/dev/kryptonreborn/blockfrost/health/HealthApiTest.kt
> +                    {
dùng kotlinx resource

2024-05-31 15:28 UTC, iTanChi requested changes

2024-05-31 15:28 UTC, iTanChi commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/ktor/Ktor.kt
> +                    Json {
Tạo json và dùng lại

2024-05-31 15:28 UTC, iTanChi commented on core/src/commonTest/kotlin/dev/kryptonreborn/blockfrost/KtorClientTest.kt
> +    fun createHealthApi(
nên đưa vào trong file test health api

2024-05-31 15:28 UTC, iTanChi commented on core/src/commonTest/kotlin/dev/kryptonreborn/blockfrost/health/HealthApiTest.kt
> +class HealthApiTest {
Nên tạo base class để kế thừa ở các file test api khác

2024-06-01 14:18 UTC, hieu-dd commented on core/src/commonTest/kotlin/dev/kryptonreborn/blockfrost/health/HealthApiTest.kt
> +class HealthApiTest {
có gì đâu mà tạo base class nhỉ

2024-06-02 14:08 UTC, iTanChi commented on core/src/appleMain/kotlin/dev/kryptonreborn/blockfrost/ktor/Ktor.apple.kt
> +    return HttpClient(Darwin) {
chỉ nên dùng engine là platform specific thôi còn các phần khác giống nhau thì đưa vào common luôn

2024-06-02 14:09 UTC, iTanChi commented on core/src/jvmMain/kotlin/dev/kryptonreborn/blockfrost/ktor/Ktor.jvm.kt
> +    return HttpClient(CIO) {
jvm với android dùng okhttp nhé

2024-06-02 14:13 UTC, iTanChi commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/base/ApiResponse.kt
> +        res.statusCode == 418 -> {
cái này sao để raw vậy nhỉ

2024-06-02 14:21 UTC, hieu-dd commented on core/src/commonMain/kotlin/dev/kryptonreborn/blockfrost/base/ApiResponse.kt
> +        res.statusCode == 418 -> {
thấy k có status nào tương đương nma trên thằng blockfrost có

2024-06-02 15:02 UTC, iTanChi commented on core/build.gradle.kts
> +                kotlin.srcDir("build/generated/kotlin")
ko cần cái này nữa?

2024-06-02 15:02 UTC, iTanChi commented on core/build.gradle.kts
> +buildkonfig {
tách line ra cho dễ check code

2024-06-02 15:04 UTC, iTanChi commented on core/build.gradle.kts
> +    val isCi = System.getenv()["CI"].toBoolean()
tách function dùng lại

2024-06-02 15:23 UTC, iTanChi approved these changes

2024-06-02 15:30 UTC, merged